### ISSUE TITLE
expected expression, found `<eof>`

### ISSUE THREAD

**Issue by realaravinth** [rust-sailfish/sailfish#58] opened 2021-05-05 06:11 UTC
First of all, thank you for this amazing crate! I've been having a fun playing around with. :)

Last night, CI builds on nightly failed with `expected expression, found '<eof>'` and I haven't been able to reproduce the issue locally on my machine. 
```bash
 error: expected expression, found `<eof>`
Error:  --> /home/runner/work/guard/guard/target/debug/build/sailfish-compiler-2f6bfe1de24fe3be/out/templates/index-ec2437792dcba84c:0:1
  |

error: non-statement macro in statement position: include
Error:   --> src/pages/panel/mod.rs:24:10
   |
24 | #[derive(TemplateOnce, Clone)]
   |          ^^^^^^^^^^^^
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

```
The failure is from a template that wasn't changed in the commits that triggered it.

Here are the logs from the failed CI runs: 
- [first run](https://github.com/mCaptcha/guard/runs/2501025878?check_suite_focus=true)
- [second run](https://github.com/mCaptcha/guard/runs/2502934112?check_suite_focus=true)

Let me know if there's something that I can do to help. Thanks!

**Comment by ggwpez** [comment] 2022-05-16 11:14
Getting the same error.  
Maybe since its using `edition = 2018`? Somehow it works locally but fails in [the CI](https://github.com/ggwpez/substrate-weight-compare/runs/6450613460?check_suite_focus=true) like you said…  
Command is [here](https://github.com/ggwpez/substrate-weight-compare/blob/c2edeb8e38b339a75ea45677f8db61bfb5d0c7d8/.github/workflows/ci.yml#L38) with rust 1.60.

**Comment by ggwpez** [comment] 2023-02-22 11:13
This is still erroring from time to time, another CI example https://github.com/ggwpez/substrate-weight-compare/actions/runs/4237520589/jobs/7363576802

**Comment by Kogia-sima** [comment] 2023-03-05 11:02
cannot reproduce an error on Lubuntu 22.04.1 LTS x86_64 (GNU libc, Intel i5-8265U @ 3.900GHz)

```
$ cargo test --locked --no-run --release --all-targets
    Finished release [optimized] target(s) in 0.15s
  Executable unittests src/main.rs (target/release/deps/swc-6ba302bf6e473a52)
  Executable tests/swc_works.rs (target/release/deps/swc_works-d9fcffd9dedb8761)
  Executable unittests src/lib.rs (target/release/deps/swc_core-91693cf945e06247)
  Executable benches/parse.rs (target/release/deps/parse-552a7381554a2310)
  Executable benches/term.rs (target/release/deps/term-1a358952933f5397)
  Executable unittests src/main.rs (target/release/deps/swc_web-aa912a30e7bf0e9b)
  Executable tests/swc_web_works.rs (target/release/deps/swc_web_works-744358ebcd6edfc4)
```

**Comment by ggwpez** [comment] 2023-03-05 18:40
Yea it is nondeterministic, only happens every now and them. There seems to be no good way to locally re-produce it.   
Something about the GitHub CI triggers it more often. Eg another one https://github.com/ggwpez/substrate-weight-compare/actions/runs/4316344945/jobs/7532000895

**Comment by w-flo** [comment] 2023-06-21 10:50
Probably not too useful info, but I wanted to add that this happens regularly for me when I save one of my project's files in VS Code, which triggers a clippy run through rust-analyzer (error is shown in the "problems" tab). Hitting Ctrl+S again, to trigger another clippy run, fixes the issue. I use a >10 year old SSD so it's not the fastest, but maybe this can rule out the "slow HDD in CI" theory?

I can't reproduce this outside of rust-analyzer though, manually running cargo run / clippy / test etc. never seems to fail. In all of my CI runs (~20 runs on gitea CI on a really slow machine, >10 year old laptop-level hardware that uses external USB HDD for storage), it hasn't failed yet either.

Maybe something both rust-analyzer and github CI have in common?

**Comment by ggwpez** [comment] 2023-06-21 10:56
It is something with the filesystem, I fixed it here https://github.com/rust-sailfish/sailfish/pull/111 but that also removes some error logs.  
Currently I am using my own fork since I dont have the time to find another solution while keeping the error prints :shrug:. But that has the problem of not being on crates,io, so its not a good solution either.

**Comment by w-flo** [comment] 2023-06-21 12:15
That's interesting! Trying to reproduce the issue, I noticed that my "cargo clippy through rust-analyzer" issue is not exactly the same, or maybe rust-analyzer somehow prints a partial error message only. I only see this part: "non-statement macro in statement position: include", no `<eof>` error message. But it's probably related or the same issue.

And while trying to figure out what exactly that error is trying to tell me, I found this: https://github.com/rust-lang/rust/issues/41497

And it turns out the "non-statement macro in statement position: include" error along with the `<eof>` error can be reproduced like this:
main.rs:
```
fn main() {
    include!("b.rs");
}
```
and b.rs should be an empty 0-byte file (`touch src/b.rs`)

So there are probably two options:

- the `out/templates/...` file is actually (still/again?) empty for some reason when the code generated by the sailfish proc macro is executed
- the file is not empty, but include!() thinks it is empty

**Comment by ggwpez** [comment] 2023-06-21 12:22
> * the `out/templates/...` file is actually (still/again?) empty for some reason when the code generated by the sailfish proc macro is executed

Yea I think there is just some race condition with the file system, since the proc macro generates a file and then reads it later.  
Maybe it is enough to flush the IO or something, did not try.

**Comment by w-flo** [comment] 2023-06-21 13:28
I think `drop(f)` as in the current code should be enough to flush the file at least for the current process (it might be a problem if rust at some point decides to run proc macros in separate processes? Not sure what guarantees OSes / filesystems usually give for file system consistency for read-after-write from different processes, and I believe there is no guarantee that sailfish proc macro execution will happen in the same process that will execute the include!() macro).

Anyway, I might have figured out the problem I was encountering when using rust-analyzer. It turns out that rust-analyzer calls cargo clippy with the "--all-targets" flag, which results in at least two check processes (apparently one for my library, and one for my test suite? Not sure what exactly is going on there) running at the same time. I added a simple eprintln!() to the sailfish proc macro and sure enough, there's a race condition where apparently two processes both write the same sailfish compilation result to the same file and then try to include!() the file shortly afterwards, which fails every now and then:
```
compiled to file "[snip]/target/debug/build/sailfish-compiler-b6ddc1e6967b5596/out/templates/login-d9afabe3f026b7df"
compiled to file "[snip]/target/debug/build/sailfish-compiler-b6ddc1e6967b5596/out/templates/login-d9afabe3f026b7df"
[... two lines for every template file I use]
```
When running just "cargo clippy" without the --all-targets flag, there is only one line of output for each template, so no race condition.

I'm not sure about the best approach to fix it. Add some more relevant data from the environment to the filename hash, like the "build type" if that is available? Or maybe add a random number instead of the hash, and then somehow identify and remove stale files on next run?

**Comment by w-flo** [comment] 2023-06-22 07:50
To address the "needs reproduction" tag, this works for me:
```
cargo new repro
cd repro/
cargo add sailfish
mkdir templates
for i in {1..50}; do echo "<% for x in 0..100 { %> <%= x %> <% } %>" >> templates/repro.stpl; done
echo "#[derive(sailfish::TemplateOnce)]#[template(path = \"repro.stpl\")] struct Repro; fn main() {}" > src/main.rs
while true; do touch src/main.rs; cargo clippy --all-targets || break; done
```
The loop will eventually hit an error on my setup, but since this is a race condition, maybe it won't work for everyone. In my actual project, it appears to be more common (maybe simply because it uses more than 1 template).

When using the linked draft PR, the bug appears to be fixed for me. And these no-change clippy runs take ~0.13 seconds instead of ~0.17 seconds, so that's cool.

**Comment by ggwpez** [comment] 2023-06-22 09:47
Yes can confirm that that script reproduces it, and can also confirm that the draft and my MR both fix.

It does not reproduce on a fast SSD, but slow HDD works. Using a limited IOPS docker container seems to work even on a fast SSD:
```bash
docker run -it --rm --device-write-iops /dev/sda:100 rust /bin/sh -c '\
rustup component add clippy; \
# Same as above \
cargo new repro; \
cd repro/; \
cargo add sailfish;
mkdir templates;
for i in {1..50}; do echo "<% for x in 0..100 { %> <%= x %> <% } %>" >> templates/repro.stpl; done;
echo "#[derive(sailfish::TemplateOnce)]#[template(path = \"repro.stpl\")] struct Repro; fn main() {}" > src/main.rs;
while true; do touch src/main.rs; cargo clippy --all-targets || break; done'
```
Outputs:
```pre
error: expected expression, found `<eof>`              
```
Also saw this error once:
```pre
error: this file contains an unclosed delimiter
 --> /repro/target/debug/build/sailfish-compiler-5b1ed890d3eb8689/out/templates/repro-ca14e6fa9f3a7064:1:4097
  |
1 | { for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (__sf_buf , x) ; __sf_rt :: render_text ! (__sf_buf , " ") ; } __sf_rt :: render_text ! (__sf_buf , "\n") ; for x in 0 .. 100 { __sf_rt :: render_text ! (__sf_buf , " ") ; __sf_rt :: render_escaped ! (_
  | -          
```

**Comment by w-flo** [comment] 2023-06-22 11:59
Thanks for testing/improving the reproducer and draft PR @ggwpez! :-)

The unclosed delimiter error is caused by the same issue, with the "shared" file already being in a partially re-written state (by the second process) at the same time the first process attempts to include!() it, so your PR or my PR should fix this as well.

**Comment by vthg2themax** [comment] 2023-06-22 19:39
@w-flo  @ggwpez First off, I want to thank you both very much for looking into this! 
As for these two open Pull Requests, I wanted to get some opinions on which one should be merged given the different approaches taken, and some pros / cons for the pull request selected?

**Comment by w-flo** [comment] 2023-06-23 06:42
Well, thanks a lot to you and Kogia-sima for maintaining this crate, and @ggwpez for figuring out where this error message originates from :-)

Personally, I'd prefer my own draft PR unless there is some way to improve the "bad error messages" problem mentioned by @Kogia-sima in the other PR. That is, I think the "caching" feature of my PR is really not that important, just a by-product of improving the existing code while keeping its general include!() approach.

Pros:

- It generates somewhat helpful error messages when using bad Rust code inside the stpl file, thanks to include!()ing the compiled template code instead of returning it directly from the proc-macro via `quote!`. I think this is the only reason why the bug still exists, otherwise @Kogia-sima would probably have merged the PR by @ggwpez some time ago.
- As I said this is not that important IMO, but it caches template compilation output, so the sailfish compiler does not have to compile all the templates again every time a cargo build / check / clippy / … runs. I believe the sailfish compiler is pretty fast though, so maybe the round-trip through the filesystem for include!() is actually slower than just running the compiler every time and directly returning the compiled code from the proc-macro without using include!(). I haven't benchmarked this because I really don't think it's important.

Cons:

- It is more complex, so there is a higher chance of introducing bugs and there is more code to maintain (I'm a KISS principle fan)
- I have no prior proc-macro experience or knowledge, so maybe my PR is doing stupid things and @Kogia-sima hates what I did to this proc-macro :-)
- The main risk is probably "proc-macro decides that it can re-use a cached compilation result file from an earlier run, when that is in fact invalid and it should instead re-compile the file", which would be very annoying and confusing for users
- Even when developers actively work on a .stpl file and compile many different intermediate versions, old compiled template files will never be deleted from the cache in the "target" directory automatically. Only something like "cargo clean" or deleting the "target" dir will get rid of them. These files are generally small though (like up to ~2x the stpl file size?), and I think it's not that common to test and compile many thousands of stpl variants without running cargo clean, and the cargo "target" dir tends to be huge anyway.
- I think the general approach is actually a bit of a hack. I'm not sure if proc-macros are supposed to be using the file system in this way? There is a comment "// FIXME: This is a silly hack to prevent output file from being tracking by cargo. Another better solution should be considered." in the existing code that seems to imply this, and maybe I should do the same in my draft PR for the new ".deps" output file. I don't really understand this though, what does cargo track when the file mtime of the output file is > than the input file and why is it bad?

So I think ideally, we'd have a clean solution like in the PR by @ggwpez, but with improved error messages when users put bad Rust code into their stpl files. I don't know if that's possible though.

**Comment by vthg2themax** [comment] 2023-06-23 13:44
I can't believe I forgot to ask @Kogia-sima for an opinon! Sorry about that! I think this sort of change should also have their opinion as well. What do you think @Kogia-sima ?

**Comment by ggwpez** [comment] 2023-06-23 17:25
I dont mind which MR we use, as long as it works and I dont have to maintain my fork anymore 🙈

**Comment by vthg2themax** [comment] 2023-06-23 17:35
Let me give it a few days to see if @Kogia-sima has any direction, and then I'll go for pulling one in. Thank you both!

**Comment by w-flo** [comment] 2023-06-27 07:28
I don't think there's a need to rush this, so if there's a chance for @Kogia-sima to voice their opinion and maybe even take a quick look at the code if we wait a bit longer (as I understand it, they're pretty busy), I don't mind delaying this for a few weeks.

**Comment by vthg2themax** [comment] 2023-07-11 17:17
Let's give it another week, and see if there's a response from @Kogia-sima on this.

**Closed** 2023-07-28 11:59 UTC
Labels: Type: Bug, Status: Need Reproduction
